"""Canonical context layer.

``AGENTS.md`` is the single source of truth. ``CLAUDE.md`` / ``GEMINI.md`` are
*generated thin pointers*: they carry no copy of AGENTS.md prose, so the three
files cannot drift. Each generated file embeds a fingerprint of AGENTS.md so a
pre-commit check can detect staleness and ``refresh`` can prove it re-synced.
"""

from __future__ import annotations

import shutil

import hashlib
from pathlib import Path

from .config import Config

GEN_MARKER = "<!-- agentctx:generated — DO NOT EDIT -->"
SOURCE_MARKER = "<!-- agentctx:source"  # followed by: <rel> sha256:<fp> -->


def source_fingerprint(canonical: Path) -> str:
    """Short, stable fingerprint of the canonical file's bytes."""
    return hashlib.sha256(canonical.read_bytes()).hexdigest()[:12]


def _relpath(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def generated_body(config: Config, target_name: str, fingerprint: str) -> str:
    """Render a generated pointer file. Deterministic for a given fingerprint."""
    root = config.root
    canonical_rel = _relpath(config.canonical, root)
    manifest_rel = _relpath(config.manifest, root)
    schema_rel = _relpath(config.handoff_schema, root)
    handoffs_rel = _relpath(config.handoffs_dir, root)
    return f"""{GEN_MARKER}
{SOURCE_MARKER} {canonical_rel} sha256:{fingerprint} -->

# {target_name} — generated pointer

This file is **auto-generated by `pigeon`**. Do not edit it by hand; edits are
overwritten on the next `pigeon refresh`. The single source of truth is
[`{canonical_rel}`]({canonical_rel}).

## Protocol for this agent

1. **Read context, don't assume it.** Start from [`{canonical_rel}`]({canonical_rel})
   and the generated manifest `{manifest_rel}` (modules, public interfaces,
   entry points, decisions, owners). The manifest replaces dumping the file tree.
2. **Retrieve instead of dumping.** To find code or prose, call
   `pigeon retrieve "<query>"`. Never paste whole files or the repo tree into
   context — retrieval returns bounded, ranked slices.
3. **Hand off via the contract, not the chat.** To pass work to another runtime
   or sub-agent, emit a handoff validated against `{schema_rel}`
   (`pigeon handoff ...`). Carry **pointers, not payloads**; the receiver
   resolves them on demand. Handoffs are appended to `{handoffs_rel}/`.
4. **Measure.** Every handoff and retrieval is token-accounted; see
   `pigeon metrics`.

Separate CLIs share no memory. The contract is the filesystem, not anyone's
context window.
"""


def context_status(config: Config) -> list[tuple[Path, str]]:
    """Report per-generated-file sync status: ``ok`` | ``stale`` | ``missing``.

    ``stale`` means the embedded fingerprint no longer matches AGENTS.md or the
    rendered body differs (e.g. the template changed).
    """
    if not config.canonical.is_file():
        raise FileNotFoundError(
            f"Canonical context file is missing: {config.canonical}. "
            "Author AGENTS.md before refreshing (new repo? run `pigeon init` first)."
        )
    fp = source_fingerprint(config.canonical)
    out: list[tuple[Path, str]] = []
    for target in config.generated:
        if not target.exists():
            out.append((target, "missing"))
            continue
        expected = generated_body(config, target.stem, fp)
        actual = target.read_text(encoding="utf-8")
        out.append((target, "ok" if actual == expected else "stale"))
    return out


# Known agent CLIs. Value = the dedicated instruction file the tool
# auto-loads, or None when it reads AGENTS.md natively (the cross-tool
# standard — Codex, opencode, Copilot) so NO pointer file is generated.
# Add a row here when a CLI needs its own filename; that is the whole
# maintenance surface, and detection keeps it honest against $PATH.
CLI_REGISTRY: dict[str, str | None] = {
    "claude": "CLAUDE.md",
    "gemini": "GEMINI.md",
    "codex": None,       # reads AGENTS.md
    "opencode": None,    # reads AGENTS.md
    "copilot": None,     # reads AGENTS.md
}

# Filenames pigeon may ever generate (for the pre-commit hook to stage).
POINTER_FILENAMES: tuple[str, ...] = tuple(
    sorted({v for v in CLI_REGISTRY.values() if v})
)


def detect_pointer_files() -> list[str]:
    """Pointer filenames for agent CLIs actually installed on PATH.

    A tool that reads AGENTS.md natively contributes nothing — the canonical
    file already serves it. Returns [] when no dedicated-file CLI is found
    (AGENTS.md still stands on its own)."""
    return [fname for binary, fname in CLI_REGISTRY.items()
            if fname and shutil.which(binary)]


def resolve_generated(config: Config) -> list[Path]:
    """The pointer files to (re)generate.

    ``paths.generated`` may be an explicit list (honored verbatim — the
    override for 'I'm adopting Codex next week' or CI without the CLI on
    PATH), or the string ``"auto"`` / absent (detect installed CLIs at every
    refresh, so the set is never one step behind your toolbox)."""
    spec = config.data["paths"].get("generated", "auto")
    names = detect_pointer_files() if spec in ("auto", None) else list(spec)
    return [config._p(n) for n in names]


def sync_context(config: Config) -> list[Path]:
    """Regenerate every pointer file from AGENTS.md. Returns written paths.

    Idempotent: re-running with an unchanged AGENTS.md rewrites byte-identical
    content. Raises if the canonical file is absent.
    """
    if not config.canonical.is_file():
        raise FileNotFoundError(
            f"Canonical context file is missing: {config.canonical}. "
            "Author AGENTS.md before refreshing (new repo? run `pigeon init` first)."
        )
    fp = source_fingerprint(config.canonical)
    written: list[Path] = []
    for target in resolve_generated(config):
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated_body(config, target.stem, fp), encoding="utf-8")
        written.append(target)
    return written
