"""Canonical context layer.

``AGENTS.md`` is the single source of truth. ``CLAUDE.md`` / ``GEMINI.md`` are
*generated thin pointers*: they carry no copy of AGENTS.md prose, so the three
files cannot drift. Each generated file embeds a fingerprint of AGENTS.md so a
pre-commit check can detect staleness and ``refresh`` can prove it re-synced.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from .config import Config

GEN_MARKER = "<!-- agentctx:generated — DO NOT EDIT -->"
SOURCE_MARKER = "<!-- agentctx:source"  # followed by: <rel> sha256:<fp> -->


def source_fingerprint(canonical: Path) -> str:
    """Short, stable fingerprint of the canonical file's bytes."""
    return hashlib.sha256(canonical.read_bytes()).hexdigest()[:12]


def _relpath(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def generated_body(config: Config, target_name: str, fingerprint: str) -> str:
    """Render a generated pointer file. Deterministic for a given fingerprint."""
    root = config.root
    canonical_rel = _relpath(config.canonical, root)
    manifest_rel = _relpath(config.manifest, root)
    schema_rel = _relpath(config.handoff_schema, root)
    handoffs_rel = _relpath(config.handoffs_dir, root)
    return f"""{GEN_MARKER}
{SOURCE_MARKER} {canonical_rel} sha256:{fingerprint} -->

# {target_name} — generated pointer

This file is **auto-generated by `pigeon`**. Do not edit it by hand; edits are
overwritten on the next `pigeon refresh`. The single source of truth is
[`{canonical_rel}`]({canonical_rel}).

## Protocol for this agent

1. **Read context, don't assume it.** Start from [`{canonical_rel}`]({canonical_rel})
   and the generated manifest `{manifest_rel}` (modules, public interfaces,
   entry points, decisions, owners). The manifest replaces dumping the file tree.
2. **Retrieve instead of dumping.** To find code or prose, call
   `pigeon retrieve "<query>"`. Never paste whole files or the repo tree into
   context — retrieval returns bounded, ranked slices.
3. **Hand off via the contract, not the chat.** To pass work to another runtime
   or sub-agent, emit a handoff validated against `{schema_rel}`
   (`pigeon handoff ...`). Carry **pointers, not payloads**; the receiver
   resolves them on demand. Handoffs are appended to `{handoffs_rel}/`.
4. **Measure.** Every handoff and retrieval is token-accounted; see
   `pigeon metrics`.

Separate CLIs share no memory. The contract is the filesystem, not anyone's
context window.
"""


def context_status(config: Config) -> list[tuple[Path, str]]:
    """Report per-generated-file sync status: ``ok`` | ``stale`` | ``missing``.

    ``stale`` means the embedded fingerprint no longer matches AGENTS.md or the
    rendered body differs (e.g. the template changed).
    """
    if not config.canonical.is_file():
        raise FileNotFoundError(
            f"Canonical context file is missing: {config.canonical}. "
            "Author AGENTS.md before refreshing (new repo? run `pigeon init` first)."
        )
    fp = source_fingerprint(config.canonical)
    out: list[tuple[Path, str]] = []
    for target in config.generated:
        if not target.exists():
            out.append((target, "missing"))
            continue
        expected = generated_body(config, target.stem, fp)
        actual = target.read_text(encoding="utf-8")
        out.append((target, "ok" if actual == expected else "stale"))
    return out


def sync_context(config: Config) -> list[Path]:
    """Regenerate every pointer file from AGENTS.md. Returns written paths.

    Idempotent: re-running with an unchanged AGENTS.md rewrites byte-identical
    content. Raises if the canonical file is absent.
    """
    if not config.canonical.is_file():
        raise FileNotFoundError(
            f"Canonical context file is missing: {config.canonical}. "
            "Author AGENTS.md before refreshing (new repo? run `pigeon init` first)."
        )
    fp = source_fingerprint(config.canonical)
    written: list[Path] = []
    for target in config.generated:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated_body(config, target.stem, fp), encoding="utf-8")
        written.append(target)
    return written
