"""Entity graph: multi-hop reasoning over files, no database.

The graph is *derived*, never hand-maintained: ``build_graph`` walks the
episodic log (handoffs) and the memory vault and emits
``.pigeon/memory/graph.json`` — committed, deterministic, regenerated by
every ``pigeon distill``.

Nodes: sessions, decisions, artifacts, agents, and memory pages (any
Markdown under ``.pigeon/memory/``, including ``entities/`` pages). Edges
carry provenance:

* ``session —decided→ decision`` and ``session —references→ artifact``
  (from each handoff, with the handoff path as provenance);
* ``session —involves→ agent`` (handoff from/to);
* ``page —links→ page`` from ``[[wiki-links]]`` in memory Markdown —
  Obsidian-compatible, so the vault stays human-browsable. A link with no
  matching page becomes a ``stub`` node: a marker for memory worth writing.

``pigeon graph "<query>" --hops N`` is a BFS over the JSON adjacency —
"what touches Vessel X, two hops out?" answered from a clone, offline.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .config import Config
from . import SCHEMA_VERSION
from . import sessions

_WIKILINK_RE = re.compile(r"\[\[([^\[\]|#]+)(?:[|#][^\[\]]*)?\]\]")
_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug(name: str) -> str:
    return _SLUG_RE.sub("-", name.strip().lower()).strip("-")


def graph_path(config: Config) -> Path:
    return config.memory_dir / "graph.json"


def build_graph(config: Config) -> dict[str, Any]:
    """Derive the graph from handoffs + memory pages; write graph.json."""
    nodes: dict[str, dict[str, Any]] = {}
    edges: list[dict[str, Any]] = []

    def node(node_id: str, node_type: str, label: str) -> str:
        nodes.setdefault(node_id, {"id": node_id, "type": node_type, "label": label})
        return node_id

    seen_edges: set[tuple] = set()

    def edge(src: str, rel: str, dst: str, provenance: str) -> None:
        key = (src, rel, dst, provenance)
        if key in seen_edges:
            return
        seen_edges.add(key)
        edges.append({"src": src, "rel": rel, "dst": dst, "provenance": provenance})

    # --- episodic layer: handoffs ---------------------------------------
    for sid in sessions.known_sids(config):
        s = node(f"session:{sid}", "session", sid)
        for rel_path, h in sessions.session_handoffs(config, sid):
            state = h.get("state") or {}
            for agent in (h.get("from"), h.get("to")):
                if agent:
                    edge(s, "involves", node(f"agent:{agent}", "agent", agent), rel_path)
            for key, val in (state.get("decisions") or {}).items():
                d = node(f"decision:{key}", "decision", key)
                e = {"src": s, "rel": "decided", "dst": d, "provenance": rel_path,
                     "value": val}
                edges.append(e)
            for artifact in state.get("artifacts") or []:
                edge(s, "references",
                     node(f"artifact:{artifact}", "artifact", artifact), rel_path)

    # --- memory vault: pages + wiki-links --------------------------------
    pages: dict[str, str] = {}  # slug -> node id
    mem = config.memory_dir
    page_files = sorted(mem.rglob("*.md")) if mem.is_dir() else []
    for path in page_files:
        rel = str(path.relative_to(config.root))
        stem = path.stem
        pid = node(f"page:{path.relative_to(mem).as_posix()}", "page", stem)
        pages.setdefault(_slug(stem), pid)
    for path in page_files:
        rel = str(path.relative_to(config.root))
        src_id = f"page:{path.relative_to(mem).as_posix()}"
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for match in _WIKILINK_RE.finditer(text):
            target = _slug(match.group(1))
            if not target:
                continue
            dst = pages.get(target) or node(f"stub:{target}", "stub", match.group(1).strip())
            edge(src_id, "links", dst, rel)

    graph = {
        "schema_version": SCHEMA_VERSION,
        "nodes": sorted(nodes.values(), key=lambda n: n["id"]),
        "edges": sorted(edges, key=lambda e: (e["src"], e["rel"], e["dst"])),
    }
    out = graph_path(config)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(graph, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
                   encoding="utf-8")
    return graph


def load_graph(config: Config) -> dict[str, Any]:
    path = graph_path(config)
    if not path.is_file():
        return build_graph(config)
    return json.loads(path.read_text(encoding="utf-8"))


def find_nodes(graph: dict[str, Any], query: str) -> list[dict[str, Any]]:
    """Nodes whose id or label contains the query (case- and slug-insensitive,
    so "North Sector" matches the page slugged as ``north-sector``)."""
    q = query.lower()
    qs = _slug(query)
    return [n for n in graph["nodes"]
            if q in n["id"].lower() or q in n["label"].lower()
            or (qs and (qs in n["id"].lower() or qs in _slug(n["label"])))]


def neighborhood(config: Config, query: str, hops: int = 1) -> dict[str, Any]:
    """BFS subgraph around every node matching ``query``."""
    graph = load_graph(config)
    starts = find_nodes(graph, query)
    if not starts:
        return {"matches": [], "nodes": [], "edges": []}
    adjacency: dict[str, list[dict[str, Any]]] = {}
    for e in graph["edges"]:
        adjacency.setdefault(e["src"], []).append(e)
        adjacency.setdefault(e["dst"], []).append(e)

    seen = {n["id"] for n in starts}
    frontier = set(seen)
    kept_edges: list[dict[str, Any]] = []
    edge_keys: set[tuple] = set()
    for _ in range(max(0, hops)):
        next_frontier: set[str] = set()
        for nid in frontier:
            for e in adjacency.get(nid, []):
                key = (e["src"], e["rel"], e["dst"], e["provenance"])
                if key not in edge_keys:
                    edge_keys.add(key)
                    kept_edges.append(e)
                for end in (e["src"], e["dst"]):
                    if end not in seen:
                        seen.add(end)
                        next_frontier.add(end)
        frontier = next_frontier
        if not frontier:
            break
    by_id = {n["id"]: n for n in graph["nodes"]}
    return {
        "matches": [n["id"] for n in starts],
        "nodes": [by_id[i] for i in sorted(seen) if i in by_id],
        "edges": sorted(kept_edges, key=lambda e: (e["src"], e["rel"], e["dst"])),
    }


def stats(config: Config) -> dict[str, Any]:
    graph = load_graph(config)
    by_type: dict[str, int] = {}
    for n in graph["nodes"]:
        by_type[n["type"]] = by_type.get(n["type"], 0) + 1
    return {"nodes": len(graph["nodes"]), "edges": len(graph["edges"]),
            "by_type": by_type, "path": str(graph_path(config).relative_to(config.root))}
