"""Skill projection: one knowledge tree, every runtime's native dialect.

Canonical skill/playbook pages live once, in ``.pigeon/memory/playbooks/``,
as Markdown with YAML frontmatter::

    ---
    name: security-audit
    description: Adversarial security review of changed code.
    tools: Read, Grep, Bash        # optional, runtime-specific
    ---
    You are a security reviewer. Refuse to approve until ...

``pigeon refresh`` *projects* every page that declares a ``name`` into each
configured runtime's native subagent format — ``.claude/agents/<name>.md``
for Claude Code first (the format its Task tool discovers), more targets as
plain config. This is the AGENTS.md -> CLAUDE.md/GEMINI.md single-sourcing
pattern one level deeper: a ``crew`` entry's ``skill:`` name resolves to the
same canonical page no matter which CLI the task runs on.

Projection never clobbers hand-written files: generated output carries a
marker, and an existing file without the marker is left alone (warned).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

from .config import Config

GEN_MARKER = "<!-- generated by pigeon refresh — edit the playbook, not this file -->"


def parse_playbook(path: Path) -> dict[str, Any] | None:
    """Frontmatter + body of a playbook page; None when it declares no name."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    match = re.match(r"^---[ \t]*\n(.*?)\n(?:---|\.\.\.)[ \t]*\n(.*)$",
                     text, re.DOTALL)
    if not match:
        return None
    try:
        meta = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        return None
    body = match.group(2)
    if not isinstance(meta, dict) or not meta.get("name"):
        return None
    return {"name": str(meta["name"]), "meta": meta, "body": body.strip()}


def playbooks(config: Config) -> list[dict[str, Any]]:
    """Every projectable playbook page (has frontmatter with a name)."""
    root = config.memory_dir / "playbooks"
    found: list[dict[str, Any]] = []
    if not root.is_dir():
        return found
    for path in sorted(root.rglob("*.md")):
        parsed = parse_playbook(path)
        if parsed:
            parsed["source"] = str(path.relative_to(config.root))
            found.append(parsed)
    return found


def _render_claude(page: dict[str, Any]) -> str:
    """Claude Code custom-subagent format: frontmatter + system prompt body."""
    meta = page["meta"]
    front: dict[str, Any] = {"name": page["name"],
                             "description": meta.get("description", page["name"])}
    if meta.get("tools"):
        front["tools"] = meta["tools"]
    head = yaml.safe_dump(front, sort_keys=False, allow_unicode=True).strip()
    return (f"---\n{head}\n---\n\n{GEN_MARKER}\n"
            f"<!-- source: {page['source']} -->\n\n{page['body']}\n")


_RENDERERS = {"claude": _render_claude}


def project_skills(config: Config) -> dict[str, Any]:
    """Write each runtime's native subagent files from the canonical pages.

    Returns {written: [...], skipped: [...]} with repo-relative paths.
    """
    targets = config.skills_cfg.get("targets", {})
    pages = playbooks(config)
    written: list[str] = []
    skipped: list[str] = []
    for runtime, target_dir in targets.items():
        renderer = _RENDERERS.get(runtime)
        if renderer is None:
            skipped.append(f"{runtime}: no renderer for this runtime yet")
            continue
        out_dir = (config.root / target_dir).resolve()
        for page in pages:
            out = out_dir / f"{page['name']}.md"
            if out.exists() and GEN_MARKER not in out.read_text(encoding="utf-8"):
                skipped.append(
                    f"{out.relative_to(config.root)}: exists and is hand-written "
                    "(no marker) — left alone"
                )
                continue
            out_dir.mkdir(parents=True, exist_ok=True)
            out.write_text(renderer(page), encoding="utf-8")
            written.append(str(out.relative_to(config.root)))
    return {"written": written, "skipped": skipped, "playbooks": len(pages)}
